# config/cucumber.yml
##YAML Template
---
default: --require features --tags ~@todo --tags ~@bug --tag ~@stress
verify: --require features --tags ~@todo --tags ~@bug --tag ~@stress -f progress
bugs: --require features --tags @bug
todo: --require features --tags @todo
all: --require features